PageLayoutExample:

<PageLayoutExample@PageLayout>:
    Games:
    # Andor:

<Games>:
    Button:
        text: "Andor Teil 1"
        id:btn1
        background_normal: root.andor1
    Button:
        text: "Andor Teil 2"
        id:btn2
        background_normal: root.andor2
    Button:
        text: "Andor Teil 3"
        id:btn3
        background_normal: root.andor3
    Button:
        text: "Bonus Legenden"
        id:btn3
        background_normal: root.bonus
