PageLayoutExample:

<PageLayoutExample@PageLayout>:
    Games:
    # Andor:

<Games@PageLayout>:
    Button:
        text: "Andor Teil 1"
        id:btn1
        background_normal: "Main/Pictures/Andor-Trilogie-1.jpg"
    Button:
        text: "Andor Teil 2"
        id:btn2
        background_normal: "Main/Pictures/Andor-Trilogie-2.jpg"
    Button:
        text: "Andor Teil 3"
        id:btn3
        background_normal: "Main/Pictures/Andor-Trilogie-3.jpg"
    Button:
        text: "Bonus Legenden"
        id:btn3
        background_normal: "Main/Pictures/Schwarze_Kogge.png"
